# Generated by Django 3.2.3 on 2021-06-12 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, unique=True)),
                ('company_url', models.URLField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(null=True)),
                ('date_leaved', models.DateField(null=True)),
                ('job_functions_description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suvjazi_app.company')),
            ],
            options={
                'verbose_name_plural': 'CompanyMemberships',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('company', models.ManyToManyField(related_name='persons_companies', through='suvjazi_app.CompanyMembership', to='suvjazi_app.Company')),
            ],
        ),
        migrations.AddField(
            model_name='companymembership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suvjazi_app.person'),
        ),
        migrations.AddField(
            model_name='company',
            name='person',
            field=models.ManyToManyField(related_name='companies_persons', through='suvjazi_app.CompanyMembership', to='suvjazi_app.Person'),
        ),
    ]
