# Generated by Django 3.2.3 on 2021-06-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='job_functions_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('person', 'company')},
        ),
    ]
