# Generated by Django 3.2.3 on 2021-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(to='suvjazi_app.Company'),
        ),
    ]
