# Generated by Django 3.2.3 on 2021-06-27 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suvjazi_app', '0002_auto_20210612_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='person',
            field=models.ManyToManyField(related_name='persons', through='suvjazi_app.CompanyMembership', to='suvjazi_app.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(related_name='companies', through='suvjazi_app.CompanyMembership', to='suvjazi_app.Company'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('co_authors', models.ManyToManyField(related_name='co_authored_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
