# Generated by Django 3.2.3 on 2021-05-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0004_alter_company_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='url',
            new_name='company_url',
        ),
    ]
