# Generated by Django 3.2.3 on 2021-05-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0005_rename_url_company_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='article_slug', max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
