# Generated by Django 3.2.3 on 2021-06-01 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0007_remove_company_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_leaved', models.DateField()),
                ('job_functions_description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suvjazi_app.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suvjazi_app.person')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(through='suvjazi_app.CompanyMembership', to='suvjazi_app.Person'),
        ),
    ]
