# Generated by Django 3.2.3 on 2021-06-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0008_auto_20210601_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymembership',
            options={'verbose_name_plural': 'CompanyMemberships'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='employees',
            new_name='person',
        ),
    ]
