# Generated by Django 3.2.3 on 2021-06-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0009_auto_20210601_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='date_joined',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='date_leaved',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='job_functions_description',
            field=models.TextField(blank=True),
        ),
    ]
