# Generated by Django 3.2.3 on 2021-06-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0010_auto_20210601_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='date_joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companymembership',
            name='date_leaved',
            field=models.DateField(),
        ),
    ]
