# Generated by Django 3.2.3 on 2021-06-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0011_auto_20210602_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
