# Generated by Django 3.2.3 on 2021-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvjazi_app', '0012_auto_20210604_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='sdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(),
        ),
    ]
