# Generated by Django 3.1.2 on 2020-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='institute',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
