# Generated by Django 3.1.2 on 2020-10-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0002_auto_20201025_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='image',
            field=models.ImageField(default='Suvjazi_app/images/institutes/default.jpg', height_field=100, upload_to='Suvjazi_app/images/institutes', width_field=200),
        ),
    ]
