# Generated by Django 3.1.2 on 2020-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0003_institute_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='image',
            field=models.ImageField(default='', height_field=100, upload_to='Suvjazi_app/images/institutes', width_field=200),
        ),
    ]
