# Generated by Django 3.1.2 on 2020-10-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0005_auto_20201025_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='image',
            field=models.ImageField(default='/templates/Suvjazi_app/images/institutes/default.jpg', upload_to='templates/Suvjazi_app/images/institutes'),
        ),
    ]
