# Generated by Django 3.1.2 on 2020-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0006_auto_20201025_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='institutes'),
        ),
    ]
