# Generated by Django 3.1.2 on 2020-10-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0008_auto_20201025_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='image',
            field=models.ImageField(default='media/images/institutes/default.jpg', upload_to='media/images/institutes'),
        ),
    ]
