# Generated by Django 3.1.2 on 2020-10-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0009_auto_20201025_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='image',
            field=models.ImageField(default='../media/images/institutes/default.jpg', upload_to='media/images/institutes'),
        ),
    ]
