# Generated by Django 3.1.2 on 2020-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0011_auto_20201025_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='image',
            field=models.ImageField(default='institutes/default.jpg', upload_to='images/institutes/'),
        ),
    ]
