# Generated by Django 3.1.2 on 2020-10-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0013_auto_20201025_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='image',
            field=models.ImageField(default='media/institutes/default.jpg', upload_to='Suvjazi_app/media/images/institutes/'),
        ),
    ]
