# Generated by Django 3.0 on 2020-10-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0014_auto_20201025_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='image',
        ),
    ]
