# Generated by Django 3.1.2 on 2020-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0015_remove_institute_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
