# Generated by Django 3.1.2 on 2020-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suvjazi_app', '0020_auto_20201026_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
