# Generated by Django 2.2.20 on 2021-07-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0002_auto_20190213_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='collectiontitle',
            name='language',
        ),
        migrations.AddField(
            model_name='collectiontitle',
            name='salary',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
