# Generated by Django 2.2.20 on 2021-07-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0003_auto_20210720_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiontitle',
            name='salary',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='mycollections.CollectionTitle')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='mycollections.Collection')),
            ],
        ),
    ]
