# Generated by Django 2.2.20 on 2021-07-20 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0004_auto_20210720_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_company', to='mycollections.CollectionTitle'),
        ),
    ]
